

INSERT INTO role(name, description, created_by, created_on, modified_by, modified_on)
VALUES ('ROLE_ADMIN', 'Admin Role', 1, UTC_TIMESTAMP(), NULL, NULL),
       ('ROLE_MERCHANT', 'Merchant Role', 1, UTC_TIMESTAMP(), NULL, NULL),
       ('ROLE_AFFILIATE', 'Affiliate Role', 1, UTC_TIMESTAMP(), NULL, NULL);

INSERT INTO business_service_category_ref(bus_svc_cat_nm,descr)
VALUES ( 'Default','Default'),
       ( 'Agriculture','Agriculture'),
       ( 'Farms','Agriculture'),
       ( 'Art Galleries','Art and Design'),
       ('Graphic Design Services','Art and Design'),
       ('Auto Repair Services','Automotive'),
       ('Car Dealerships','Automotive'),
       ('E-learning Platforms','Education and Training'),
       ('Schools and Universities','Education and Training'),
       ('Training Centers','Education and Training'),
       ('Power Plants','Energy and Utilities'),
       ('Renewable Energy Companies','Energy and Utilities'),
       ('Utility Services','Energy and Utilities'),
       ('Advertising Agencies','Entertainment and Media'),
       ('Film and Television Production','Entertainment and Media'),
       ('Music and Event Management','Entertainment and Media'),
       ('Environmental Consulting','Environmental Services'),
       ('Recycling Companies','Environmental Services'),
       ('Clothing Stores','Fashion and Apparel'),
       ('Fashion Design','Fashion and Apparel'),
       ('Banks','Finance and Banking'),
       ('Insurance Companies','Finance and Banking'),
       ('Investment Firms','Finance and Banking'),
       ('Cafes','Food and Beverage'),
       ('Food Delivery Services','Food and Beverage'),
       ('Restaurants','Food and Beverage'),
       ('Municipal Services','Government Services'),
       ('Public Administration','Government Services'),
       ('Fitness Centers','Health and Wellness'),
       ('Healthcare Providers','Health and Wellness'),
       ('Wellness Spas','Health and Wellness'),
       ('Event Planning Services','Hospitality'),
       ('Hotels','Hospitality'),
       ('Travel Agencies','Hospitality'),
       ('Automobile Manufacturing','Manufacturing'),
       ('Consumer Goods Production','Manufacturing'),
       ('Electronics','Manufacturing'),
       ('Industrial Equipment Manufacturing','Manufacturing'),
       ('Charities','Nonprofit Organizations'),
       ('Foundations','Nonprofit Organizations'),
       ('NGOs','Nonprofit Organizations'),
       ('Not Listed','Other'),
       ('Beauty Product Manufacturing','Personal Care and Beauty'),
       ('Salons','Personal Care and Beauty'),
       ('Accounting Firms','Professional Services'),
       ('Consulting Services','Professional Services'),
       ('Law Firms','Professional Services'),
       ('Construction Companies','Real Estate'),
       ('Property Management','Real Estate'),
       ('Real Estate Agencies','Real Estate'),
       ('Department Stores','Retail'),
       ('E-commerce Businesses','Retail'),
       ('Specialty Stores','Retail'),
       ('Housing and Construction','Services'),
       ('Professional Services','Services'),
       ('Community centers','Social and Community Services'),
       ('Social work agencies','Social and Community Services'),
       ('IT Consulting','Technology and IT'),
       ('Software Development','Technology and IT'),
       ('Internet Service Providers Mobile carriers','Telecommunications'),
       ('Airlines','Transportation'),
       ('Ride-sharing Services','Transportation'),
       ('Shipping Companies','Transportation');

INSERT INTO campaign_category_ref( camp_cat_nm, descr)
VALUES ( 'Default','Default.'),
       ( 'Brand Awareness','Introducing a new brand or increasing visibility for an existing one. Creating recognition and recall among the target audience.'),
       ( 'Product Launch','Introducing a new product to the market. Generating excitement and interest around the new offering.'),
       ( 'Lead Generation','Collecting contact information from potential customers. Building a database for future marketing efforts.'),
       ( 'Sales Promotion','Boosting sales within a specific time frame. Offering discounts, promotions, or limited-time offers.'),
       ('Customer Retention','Encouraging repeat business from existing customers. Building loyalty and reducing customer churn.'),
       ('Educational Campaign','Providing information about a product, service, or industry. Enhancing customer knowledge and understanding.'),
       ('Rebranding','Changing the brand image, logo, or messaging. Shifting perceptions and reintroducing the brand to the market.'),
       ('Community Engagement','Building a sense of community around the brand. Fostering engagement and interaction with the target audience.'),
       ('Social Cause Awareness','Associating the brand with a social or environmental cause. Increasing awareness and support for a particular issue.'),
       ('Market Expansion','Entering new markets or demographics. Increasing the brands reach and customer base.'),
       ('Thought Leadership','Establishing the brand or key individuals as industry experts. Providing valuable insights and expertise to the target audience.'),
       ('Event Promotion','Driving attendance or participation in an event. Creating awareness and excitement around a specific happening.'),
       ('Online Engagement','Increasing online interactions, such as likes, shares, and comments. Building a strong online presence and community.'),
       ('Influencer Collaboration','Leveraging influencers to promote the brand or product. Capitalizing on the influencers audience and credibility.'),
       ('Customer Feedback','Gathering feedback and opinions from customers. Improving products, services, or overall customer experience.'),
       ('Competitive Positioning','Differentiating the brand from competitors. Communicating unique selling propositions.'),
       ('Crisis Management','Addressing and mitigating negative publicity or crises. Restoring or maintaining the brands reputation.'),
       ('Employee Advocacy','Encouraging employees to promote the brand. Leveraging the internal team as brand ambassadors.'),
       ('Product Awareness','Increasing awareness of specific products or product lines. Highlighting features, benefits, and use cases.'),
       ('Political Advocacy','Promoting a political candidate, party, or cause. Mobilizing support and influencing public opinion.');
